# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# Forr more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
#     - name: Cache npm dependencies
#       uses: actions/cache@v1
#       with:
#         path: ~/.npm
#         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}}
#         restore-keys: |
#           ${{ runner.os }}-node-
          
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
         path: ~/.yarn
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
          ${{ runner.os }}-yarn-
          
#     - name: Cache yarn dependencies
#       uses: actions/cache@v2
#       with:
#         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-yarn-


    - run: yarn install
    - run: yarn build   
#     - run: npm i
#     - run: npm build
#     - run: pm2 stop 0
#     - run: npm install
#     - run: pm2 start 0

